version: '2.1'

services:
  localstack:
    privileged: true
    container_name: "localstack-container"
    image: localstack/localstack:latest
    ports:
      - "443:443"
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    env_file:
      - ./.localstack/.env.localstack
      - ./.localstack/.env.localstack.secret
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock            
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  docker-sls:  
    build: .    
    container_name: "sls-container"
    working_dir: /var/task
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
      - AWS_REGION     
      - KINESIS_ENDPOINT 
      - DOCKER_HOST=unix:///var/run/docker.sock
      # LOCALSTACK_REGION and LOCALSTACK_STAGE are used in fixture creation
      - LOCALSTACK_REGION
      - LOCALSTACK_STAGE
      - LISTEN_STREAM_NAME
      - PUBLISH_STREAM_NAME
    volumes:      
      - "./.localstack:/var/task/.localstack"
      - "./functions:/var/task/functions"
      - "./logs:/var/task/logs"
      - "./test:/var/task/test"
      - "./serverless.yml:/var/task/serverless.yml"
      - "./stages:/var/task/stages"
      - "./variables.yml:/var/task/variables.yml"
      - "/var/run/docker.sock:/var/run/docker.sock" 
    depends_on: 
      - localstack
