functions:
  hello:          
    handler: functions/hello/handler.hello
    memorySize: 512    
    package:
      exclude:
        - ./**
      include:
        - functions/hello/handler.py               


Resources:  
  AroundTheWorldConsumer:
    Type: AWS::Kinesis::StreamConsumer
    Properties:
      ConsumerName: ${self:provider.stackName}-AroundTheWorldStreamConsumer
      StreamARN: ${self:custom.source.streamArn}   

Outputs:
  SimpleOutput:
    Description: Dummy Output
    Value:
      "whatever"
    Export:
      Name: "whatever-name"

lambdaPolicyXRay:
  Effect: Allow
  Action:
    - xray:*    
  Resource: "*"

lambdaPolicyKinesisRead:
  Effect: Allow
  Action:
    - kinesis:*    
  Resource: "*"

lambdaPolicyKinesisWrite:
  Effect: Allow
  Action:
    - kinesis:*    
  Resource: "*"

lambdaPolicyKmsSource:
  Effect: Allow
  Action:    
    - kms:*    
  #TODO Parameterize  (maybe an SSM use case here)
  Resource: 
    - "*"

lambdaPolicyKmsSink:
  Effect: Allow
  Action:    
    - kms:*    
  #TODO Parameterize  (maybe an SSM use case here)
  Resource: 
    - "*"
  
lambdaPolicyCloudWatch:
  Effect: Allow
  Action:
    - logs:*    
  Resource: "*"
